const sura114 = [
  {
    number: 114,
    name: "سُورَةُ النَّاسِ",
    englishName: "An-Naas",
    englishNameTranslation: "Mankind",
    revelationType: "Meccan",
    numberOfAyahs: 6,
    ayahs: [
      {
        number: 6231,
        text: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ",
        numberInSurah: 1,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 556,
        hizbQuarter: 240,
        sajda: false,
      },
      {
        number: 6232,
        text: "مَلِكِ ٱلنَّاسِ",
        numberInSurah: 2,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 556,
        hizbQuarter: 240,
        sajda: false,
      },
      {
        number: 6233,
        text: "إِلَٰهِ ٱلنَّاسِ",
        numberInSurah: 3,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 556,
        hizbQuarter: 240,
        sajda: false,
      },
      {
        number: 6234,
        text: "مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ",
        numberInSurah: 4,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 556,
        hizbQuarter: 240,
        sajda: false,
      },
      {
        number: 6235,
        text: "ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ",
        numberInSurah: 5,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 556,
        hizbQuarter: 240,
        sajda: false,
      },
      {
        number: 6236,
        text: "مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ",
        numberInSurah: 6,
        juz: 30,
        manzil: 7,
        page: 604,
        ruku: 556,
        hizbQuarter: 240,
        sajda: false,
      },
    ],
    edition: {
      identifier: "quran-uthmani",
      language: "ar",
      name: "القرآن الكريم برسم العثماني",
      englishName: "Uthmani",
      format: "text",
      type: "quran",
      direction: "rtl",
    },
  },
];
